//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentWebApp.GetCarServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://j2ee.netbeans.org/wsdl/CarRentalBPEL/src/GetCarWSDL", ConfigurationName="GetCarServiceReference.GetCarWSDLPortType")]
    public interface GetCarWSDLPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="part1")]
        CarRentWebApp.GetCarServiceReference.CarComplexType GetCarWSDLOperation(int getCarId, string getCarProviderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="part1")]
        System.Threading.Tasks.Task<CarRentWebApp.GetCarServiceReference.CarComplexType> GetCarWSDLOperationAsync(int getCarId, string getCarProviderId);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.netbeans.org/schema/CarRentalSchema")]
    public partial class CarComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string typeField;
        
        private string brandField;
        
        private string transmissionField;
        
        private int numberOfPeopleField;
        
        private int numberOfBaggageField;
        
        private double pricePerDayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string brand {
            get {
                return this.brandField;
            }
            set {
                this.brandField = value;
                this.RaisePropertyChanged("brand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string transmission {
            get {
                return this.transmissionField;
            }
            set {
                this.transmissionField = value;
                this.RaisePropertyChanged("transmission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int numberOfPeople {
            get {
                return this.numberOfPeopleField;
            }
            set {
                this.numberOfPeopleField = value;
                this.RaisePropertyChanged("numberOfPeople");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int numberOfBaggage {
            get {
                return this.numberOfBaggageField;
            }
            set {
                this.numberOfBaggageField = value;
                this.RaisePropertyChanged("numberOfBaggage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double pricePerDay {
            get {
                return this.pricePerDayField;
            }
            set {
                this.pricePerDayField = value;
                this.RaisePropertyChanged("pricePerDay");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetCarWSDLPortTypeChannel : CarRentWebApp.GetCarServiceReference.GetCarWSDLPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCarWSDLPortTypeClient : System.ServiceModel.ClientBase<CarRentWebApp.GetCarServiceReference.GetCarWSDLPortType>, CarRentWebApp.GetCarServiceReference.GetCarWSDLPortType {
        
        public GetCarWSDLPortTypeClient() {
        }
        
        public GetCarWSDLPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetCarWSDLPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetCarWSDLPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetCarWSDLPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CarRentWebApp.GetCarServiceReference.CarComplexType GetCarWSDLOperation(int getCarId, string getCarProviderId) {
            return base.Channel.GetCarWSDLOperation(getCarId, getCarProviderId);
        }
        
        public System.Threading.Tasks.Task<CarRentWebApp.GetCarServiceReference.CarComplexType> GetCarWSDLOperationAsync(int getCarId, string getCarProviderId) {
            return base.Channel.GetCarWSDLOperationAsync(getCarId, getCarProviderId);
        }
    }
}
