//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentWebApp.GetBookedServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://j2ee.netbeans.org/wsdl/CarRentalBPEL/src/GetBookedRents", ConfigurationName="GetBookedServiceReference.GetBookedRentsPortType")]
    public interface GetBookedRentsPortType {
        
        // CODEGEN: Parameter 'booked' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="booked")]
        CarRentWebApp.GetBookedServiceReference.output1 GetBookedRentsOperation(CarRentWebApp.GetBookedServiceReference.input1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CarRentWebApp.GetBookedServiceReference.output1> GetBookedRentsOperationAsync(CarRentWebApp.GetBookedServiceReference.input1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rentcar.hub.com/")]
    public partial class carRentLog : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bookedDateField;
        
        private string idField;
        
        private string providerUUIDField;
        
        private string statusField;
        
        private string userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string bookedDate {
            get {
                return this.bookedDateField;
            }
            set {
                this.bookedDateField = value;
                this.RaisePropertyChanged("bookedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string providerUUID {
            get {
                return this.providerUUIDField;
            }
            set {
                this.providerUUIDField = value;
                this.RaisePropertyChanged("providerUUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBookedRentsOperation", WrapperNamespace="http://j2ee.netbeans.org/wsdl/CarRentalBPEL/src/GetBookedRents", IsWrapped=true)]
    public partial class input1 {
        
        public input1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBookedRentsOperationResponse", WrapperNamespace="http://j2ee.netbeans.org/wsdl/CarRentalBPEL/src/GetBookedRents", IsWrapped=true)]
    public partial class output1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CarRentWebApp.GetBookedServiceReference.carRentLog[] booked;
        
        public output1() {
        }
        
        public output1(CarRentWebApp.GetBookedServiceReference.carRentLog[] booked) {
            this.booked = booked;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetBookedRentsPortTypeChannel : CarRentWebApp.GetBookedServiceReference.GetBookedRentsPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetBookedRentsPortTypeClient : System.ServiceModel.ClientBase<CarRentWebApp.GetBookedServiceReference.GetBookedRentsPortType>, CarRentWebApp.GetBookedServiceReference.GetBookedRentsPortType {
        
        public GetBookedRentsPortTypeClient() {
        }
        
        public GetBookedRentsPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetBookedRentsPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetBookedRentsPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetBookedRentsPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentWebApp.GetBookedServiceReference.output1 CarRentWebApp.GetBookedServiceReference.GetBookedRentsPortType.GetBookedRentsOperation(CarRentWebApp.GetBookedServiceReference.input1 request) {
            return base.Channel.GetBookedRentsOperation(request);
        }
        
        public CarRentWebApp.GetBookedServiceReference.carRentLog[] GetBookedRentsOperation() {
            CarRentWebApp.GetBookedServiceReference.input1 inValue = new CarRentWebApp.GetBookedServiceReference.input1();
            CarRentWebApp.GetBookedServiceReference.output1 retVal = ((CarRentWebApp.GetBookedServiceReference.GetBookedRentsPortType)(this)).GetBookedRentsOperation(inValue);
            return retVal.booked;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentWebApp.GetBookedServiceReference.output1> CarRentWebApp.GetBookedServiceReference.GetBookedRentsPortType.GetBookedRentsOperationAsync(CarRentWebApp.GetBookedServiceReference.input1 request) {
            return base.Channel.GetBookedRentsOperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentWebApp.GetBookedServiceReference.output1> GetBookedRentsOperationAsync() {
            CarRentWebApp.GetBookedServiceReference.input1 inValue = new CarRentWebApp.GetBookedServiceReference.input1();
            return ((CarRentWebApp.GetBookedServiceReference.GetBookedRentsPortType)(this)).GetBookedRentsOperationAsync(inValue);
        }
    }
}
