//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentWebApp.GetBookedServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://j2ee.netbeans.org/wsdl/CarRentalBPEL/src/GetBookedRentsWSDL", ConfigurationName="GetBookedServiceReference.GetBookedRentsWSDLPortType")]
    public interface GetBookedRentsWSDLPortType {
        
        // CODEGEN: Generating message contract since message part namespace (http://rentcar.hub.com/) does not match the default value ()
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getRegistryResponse")]
        CarRentWebApp.GetBookedServiceReference.output1 GetBookedRentsWSDLOperation(CarRentWebApp.GetBookedServiceReference.input1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CarRentWebApp.GetBookedServiceReference.output1> GetBookedRentsWSDLOperationAsync(CarRentWebApp.GetBookedServiceReference.input1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rentcar.hub.com/")]
    public partial class carRentLog : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bookedDateField;
        
        private string idField;
        
        private string providerUUIDField;
        
        private string statusField;
        
        private string userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string bookedDate {
            get {
                return this.bookedDateField;
            }
            set {
                this.bookedDateField = value;
                this.RaisePropertyChanged("bookedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string providerUUID {
            get {
                return this.providerUUIDField;
            }
            set {
                this.providerUUIDField = value;
                this.RaisePropertyChanged("providerUUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBookedRentsWSDLOperation", WrapperNamespace="http://j2ee.netbeans.org/wsdl/CarRentalBPEL/src/GetBookedRentsWSDL", IsWrapped=true)]
    public partial class input1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string inputBookedRents;
        
        public input1() {
        }
        
        public input1(string inputBookedRents) {
            this.inputBookedRents = inputBookedRents;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBookedRentsWSDLOperationResponse", WrapperNamespace="http://j2ee.netbeans.org/wsdl/CarRentalBPEL/src/GetBookedRentsWSDL", IsWrapped=true)]
    public partial class output1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rentcar.hub.com/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://rentcar.hub.com/")]
        [System.Xml.Serialization.XmlArrayItemAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CarRentWebApp.GetBookedServiceReference.carRentLog[] getRegistryResponse;
        
        public output1() {
        }
        
        public output1(CarRentWebApp.GetBookedServiceReference.carRentLog[] getRegistryResponse) {
            this.getRegistryResponse = getRegistryResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetBookedRentsWSDLPortTypeChannel : CarRentWebApp.GetBookedServiceReference.GetBookedRentsWSDLPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetBookedRentsWSDLPortTypeClient : System.ServiceModel.ClientBase<CarRentWebApp.GetBookedServiceReference.GetBookedRentsWSDLPortType>, CarRentWebApp.GetBookedServiceReference.GetBookedRentsWSDLPortType {
        
        public GetBookedRentsWSDLPortTypeClient() {
        }
        
        public GetBookedRentsWSDLPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetBookedRentsWSDLPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetBookedRentsWSDLPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetBookedRentsWSDLPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentWebApp.GetBookedServiceReference.output1 CarRentWebApp.GetBookedServiceReference.GetBookedRentsWSDLPortType.GetBookedRentsWSDLOperation(CarRentWebApp.GetBookedServiceReference.input1 request) {
            return base.Channel.GetBookedRentsWSDLOperation(request);
        }
        
        public CarRentWebApp.GetBookedServiceReference.carRentLog[] GetBookedRentsWSDLOperation(string inputBookedRents) {
            CarRentWebApp.GetBookedServiceReference.input1 inValue = new CarRentWebApp.GetBookedServiceReference.input1();
            inValue.inputBookedRents = inputBookedRents;
            CarRentWebApp.GetBookedServiceReference.output1 retVal = ((CarRentWebApp.GetBookedServiceReference.GetBookedRentsWSDLPortType)(this)).GetBookedRentsWSDLOperation(inValue);
            return retVal.getRegistryResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentWebApp.GetBookedServiceReference.output1> CarRentWebApp.GetBookedServiceReference.GetBookedRentsWSDLPortType.GetBookedRentsWSDLOperationAsync(CarRentWebApp.GetBookedServiceReference.input1 request) {
            return base.Channel.GetBookedRentsWSDLOperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentWebApp.GetBookedServiceReference.output1> GetBookedRentsWSDLOperationAsync(string inputBookedRents) {
            CarRentWebApp.GetBookedServiceReference.input1 inValue = new CarRentWebApp.GetBookedServiceReference.input1();
            inValue.inputBookedRents = inputBookedRents;
            return ((CarRentWebApp.GetBookedServiceReference.GetBookedRentsWSDLPortType)(this)).GetBookedRentsWSDLOperationAsync(inValue);
        }
    }
}
