<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="BechCarRentalWSWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/BechCarRentalWSWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/BechCarRentalWSWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://WS.BechCarRental/">
    <import location="http://localhost:8080/BechCarRentalWS/BechCarRentalWS?wsdl" namespace="http://WS.BechCarRental/"/>
    <plnk:partnerLinkType name="BechCarRentalWSLinkType">
        <plnk:role name="BechCarRentalWSRole" portType="ns:BechCarRentalWS"/>
    </plnk:partnerLinkType>
</definitions>
