<?xml version="1.0" encoding="UTF-8"?>
<definitions name="CarRentalWSDL" targetNamespace="http://j2ee.netbeans.org/wsdl/CarRentalBPEL/src/CarRentalWSDL"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
             xmlns:tns="http://j2ee.netbeans.org/wsdl/CarRentalBPEL/src/CarRentalWSDL" 
             xmlns:ns="http://rentcar.hub.com/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns0="http://WS.BechCarRental/" xmlns:ns1="http://WS.KutzCarRental/">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/CarRentalBPEL/src/CarRentalWSDL">
            <xsd:import namespace="http://rentcar.hub.com/" schemaLocation="http://localhost:8080/HubService/HubService?xsd=1"/>
            <xsd:import namespace="http://WS.BechCarRental/" schemaLocation="http://localhost:8080/BechCarRentalWS/BechCarRentalWS?xsd=1"/>
            <xsd:import namespace="http://WS.KutzCarRental/" schemaLocation="http://localhost:8080/KutzCarRentalWS/KutzCarRentalWS?xsd=1"/>
        </xsd:schema>
    </types>
    <message name="CarRentalWSDLOperationRequest">
        <part name="operationName" type="xsd:int"/>
        <part name="providerId" type="xsd:int"/>
    </message>
    <message name="CarRentalWSDLOperationResponse">
        <part name="providers" type="ns:getRentalProvidersResponse"/>
        <part name="bechCars" type="ns0:getCarsResponse"/>
        <part name="kutzCars" type="ns1:getCarsResponse"/>
    </message>
    <portType name="CarRentalWSDLPortType">
        <operation name="CarRentalWSDLOperation">
            <input name="input1" message="tns:CarRentalWSDLOperationRequest"/>
            <output name="output1" message="tns:CarRentalWSDLOperationResponse"/>
        </operation>
    </portType>
    <binding name="CarRentalWSDLBinding" type="tns:CarRentalWSDLPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="CarRentalWSDLOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/CarRentalBPEL/src/CarRentalWSDL"/>
            </input>
            <output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/CarRentalBPEL/src/CarRentalWSDL"/>
            </output>
        </operation>
    </binding>
    <service name="CarRentalWSDLService">
        <port name="CarRentalWSDLPort" binding="tns:CarRentalWSDLBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/CarRentalWSDLService/CarRentalWSDLPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="CarRentalWSDL">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="CarRentalWSDLPortTypeRole" portType="tns:CarRentalWSDLPortType"/>
    </plnk:partnerLinkType>
</definitions>
