<?xml version="1.0" encoding="UTF-8"?>
<definitions name="GetBookedRentsWSDL" targetNamespace="http://j2ee.netbeans.org/wsdl/CarRentalBPEL/src/GetBookedRentsWSDL"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/CarRentalBPEL/src/GetBookedRentsWSDL" xmlns:ns="http://rentcar.hub.com/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/CarRentalBPEL/src/GetBookedRentsWSDL">
            <xsd:import namespace="http://rentcar.hub.com/" schemaLocation="file:/C:/Users/Irving/Documents/Git/TopicosWeb/CarRentalBPEL/retrieved/src/localhost_8080/HubService/HubService.xsd_1.xsd"/>
        </xsd:schema>
    </types>
    <message name="GetBookedRentsWSDLOperationRequest">
        <part name="inputBookedRents" type="xsd:string"/>
    </message>
    <message name="GetBookedRentsWSDLOperationResponse">
        <part name="bookedResponses" element="ns:getRegistryResponse"/>
    </message>
    <portType name="GetBookedRentsWSDLPortType">
        <operation name="GetBookedRentsWSDLOperation">
            <input name="input1" message="tns:GetBookedRentsWSDLOperationRequest"/>
            <output name="output1" message="tns:GetBookedRentsWSDLOperationResponse"/>
        </operation>
    </portType>
    <binding name="GetBookedRentsWSDLBinding" type="tns:GetBookedRentsWSDLPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="GetBookedRentsWSDLOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/CarRentalBPEL/src/GetBookedRentsWSDL"/>
            </input>
            <output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/CarRentalBPEL/src/GetBookedRentsWSDL"/>
            </output>
        </operation>
    </binding>
    <service name="GetBookedRentsWSDLService">
        <port name="GetBookedRentsWSDLPort" binding="tns:GetBookedRentsWSDLBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/GetBookedRentsWSDLService/GetBookedRentsWSDLPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="GetBookedRentsWSDL">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="GetBookedRentsWSDLPortTypeRole" portType="tns:GetBookedRentsWSDLPortType"/>
    </plnk:partnerLinkType>
</definitions>
