<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="HubServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/HubServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/HubServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://rentcar.hub.com/">
    <import location="http://192.168.1.77:8080/HubService/HubService?wsdl" namespace="http://rentcar.hub.com/"/>
    <plnk:partnerLinkType name="HubServiceLinkType">
        <plnk:role name="HubServiceRole" portType="ns:HubService"/>
    </plnk:partnerLinkType>
</definitions>
