<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="KutzCarRentalWSWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/KutzCarRentalWSWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/KutzCarRentalWSWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://WS.KutzCarRental/">
    <import location="http://localhost:8080/KutzCarRentalWS/KutzCarRentalWS?wsdl" namespace="http://WS.KutzCarRental/"/>
    <plnk:partnerLinkType name="KutzCarRentalWSLinkType">
        <plnk:role name="KutzCarRentalWSRole" portType="ns:KutzCarRentalWS"/>
    </plnk:partnerLinkType>
</definitions>
